trigger: 
- main

pool: 
  name: Linux-MSI-local

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM - TestEnvironment
  environment: 
   name: TestEnvironment
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"