variables:
  environmentName: 'EmptyEnvironment'

resources:
  pipelines:
    - pipeline: demopipelines-resource
      source: demopipelines


jobs:
  # Track deployments on the environment.
- deployment: DeployTest
  displayName: test deployment
  pool:
    name: 'Linux-MSI-local'
  # Creates an environment if it doesn't exist.
  environment: $(environmentName)
  strategy:
    # Default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: echo my first deployment
        - download: demopipelines-resource
          artifact: drop-ontheedge